server:
  port: 8080

spring:
  application:
    name: sys-status-server
  datasource:
    url: jdbc:mysql://localhost:3306/sys_status?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

sys-status:
  agent:
    heartbeat-warn-seconds: 20
    heartbeat-offline-seconds: 60
    snapshot-retention-days: 7
